"""add model column to spans

Revision ID: 28cb78774149
Revises: ac0911b6102a
Create Date: 2026-07-22 16:11:52.111415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28cb78774149'
down_revision: Union[str, Sequence[str], None] = 'ac0911b6102a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spans', sa.Column('model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spans', 'model')
    # ### end Alembic commands ###
